/**
 * Sandbox Test Environment
 * 
 * This is a sample file that serves as a playground to test the generated NocoDB client.
 * To beging, copy this file to a new one with the name 'main.ts' and modify it to suit your needs.
 * 
 * Instructions:
 * 1. Generate your client using `npm run gen` (or `npm run test:full-generation` for dev).
 * 2. Import your generated project client from the output directory.
 *    Example: import { MyStoreClient } from '../testOutput/my-store';
 * 3. Configure the client with your NocoDB URL and API Token.
 * 4. Use the client to generic interactions with your tables.
 */

// --- CONFIGURATION ---
import * as dotenv from 'dotenv';
import * as path from 'path';
import { Api, TableClient } from '../testOutput/client-base';

// Load environment variables from test.env
const envPath = path.resolve(__dirname, '../test.env');
dotenv.config({ path: envPath });

console.log('--- Sandbox Test ---');
console.log('Environment loaded from:', envPath);

// --- EXAMPLE MOCK SETUP (FAKE TEST CASE) ---
// This mocks what the generated code would look like for a 'My Store' project.

export interface Products {
  Name?: string;
  Price?: number;
}

export class MyStoreClient extends Api {
  public Products: TableClient<Products>;

  constructor(config: { baseURL: string; token: string }) {
    super(config);
    this.Products = new TableClient(this.client, 'Products');
  }
}
// --- END EXAMPLE MOCK SETUP ---
/**
 * This mock setup should be replaced by the client generated by 'npm run gen'
 * import { MyStoreClient } from '../testOutput/my-store';
 */
// --- RUN SANDBOX ---

async function runSandbox() {
  const token = process.env.XC_TOKEN;
  const baseUrl = (process.env.NOCODB_URL || 'http://localhost:8080').replace(/\/$/, '');

  if (!token) {
    console.error('Error: XC_TOKEN is not set in test.env');
    return;
  }

  // Initialize the client
  console.log('Initializing MyStoreClient...');
  const db = new MyStoreClient({
      baseURL: baseUrl,
      token: token
  });

  try {
    // --- INTERACT WITH DATA ---
    // Note: This will likely fail with 404 if 'Products' table doesn't exist on your NocoDB instance.
    // This is just a demonstration of the client usage pattern.
    
    console.log('\n--- Listing Products ---');
    console.log('(Note: This call will fail if the table "Products" does not exist)');
    
    try {
        const products = await db.Products.list({ limit: 10 });
        console.log(`Found ${products.list.length} products.`);
        console.log(products.list);
    } catch (e: any) {
        console.warn('List failed as expected (Mock Table):', e.message);
    }

    /*
    console.log('\n--- Creating Product ---');
    await db.Products.create({
      Name: 'New Product',
      Price: 99.99
    }); 
    */

  } catch (error: any) {
    console.error('Sandbox execution failed:', error.message);
  }
}

runSandbox();
